name: Build-Pipeline

on:
  push:
    branches:
      - master
jobs:
  Prerequisite:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Check path
        run: | 
          echo pwd
  BuildApplicationAndImage:
    needs:
      - Prerequisite
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          overwrite-settings: false
      - name: Checking directory
        run: ls -lrt
      - name: Gradle Build
        run: gradle clean build
      - name: Building Image
        run:  docker build .
  BuildImage:
    needs:
      - Build
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Checking current directory
        run: pwd
      - name: Checking current directory files
        run: ls -lrt
#      - name: Building Image
#        run:  docker build .
  PushImage:
    needs:
      - BuildImage
    runs-on: [ubuntu-latest]
    env:
      username: ${{secrets.DOCKER_USE}}
      password: ${{secrets.DOCKER_SECRET}}
    steps:
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push image to docker
        run: docker push