name: Build-Pipeline

on:
  push:
    branches:
      - master
jobs:
  Prerequisite:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Check path
        run: pwd
